//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public int MenuCardID { get; set; }
        public int Quantity { get; set; }
        public string CustomMenuName { get; set; }
        public decimal CustomMenuPrice { get; set; }
        public string Remarks { get; set; }
    
        public virtual MenuCard MenuCard { get; set; }
        public virtual OrderKassa Order { get; set; }
    }
}
