//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationTable
    {
        public int ReservationTableID { get; set; }
        public int ReservationID { get; set; }
        public int TableID { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual TableSeat TableSeat { get; set; }
    }
}
