//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public long ID { get; set; }
        public string LogType { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public string LogDesc { get; set; }
        public string LogUser { get; set; }
    }
}
