//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pos.Desktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableSeat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableSeat()
        {
            this.Order = new HashSet<OrderKassa>();
            this.ReservationTable = new HashSet<ReservationTable>();
        }
    
        public int TableID { get; set; }
        public int TableNumber { get; set; }
        public string TableType { get; set; }
        public string TableStatus { get; set; }
        public string TableName { get; set; }
        public bool IsDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderKassa> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservationTable> ReservationTable { get; set; }
    }
}
